[package]
name = "ol_cli"
authors = []
version = "0.1.0"
edition = "2018"

[dependencies]
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
reqwest = { version = "0.10.6", features = ["blocking", "json"], default_features = false }
miner = { path = "../miner", version = "0.1.0" }
cli = { path = "../testsuite/cli/", version = "0.1.0" }
libra-types = { path = "../types/", version= "0.1.0"}
num-format = "0.4.0"
resource-viewer = { path = "../language/tools/resource-viewer", version = "0.1.0" }
anyhow = "1.0"

[dependencies.abscissa_core]
version = "0.5.2"
# optional: use `gimli` to capture backtraces
# see https://github.com/rust-lang/backtrace-rs/issues/189
# features = ["gimli-backtrace"]

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
once_cell = "1.2"

