name: Experiment

on:
  push:
    branches: [ v6-ci-rebased ]
    
jobs:
  build:
    name: Write
    runs-on: ubuntu-latest
    steps:
      - name: write file
        run: echo "test this" > ./newfile.txt
  read:
    name: Read
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: read file
        run: cat./newfile.txt

