name: On push

on:
  push:
    branches: [ v6-ci-rebased ]

jobs:
  install:
    uses: ./.github/workflows/ci-install.yaml
  tools:
    needs: install
    uses: ./.github/workflows/tools.yaml
  transactional:
    needs: install
    uses: ./.github/workflows/transactional-tests.yaml
  smoke:
    needs: install
    uses: ./.github/workflows/smoke.yaml