name: On push

on:
  push:
    branches: [ v6-ci-rebased ]

jobs:
  read:
    runs-on: ubuntu-latest
    steps:
      # - name: Check out
      #   uses: actions/checkout@v3
      - name: Reads
        uses: ./.github/workflows/ci-exp-install.yaml    
