name: Publish

on:
  push:
#    tags:
#      - '*'
     branch:
       - cargo-deb

jobs:
  publish:
    name: Publish for Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Deb Build
        #uses: ebbflow-io/cargo-deb-armv7-debian@1.47.0-1
        uses: ebbflow-io/cargo-deb-amd64-ubuntu@1.0
        with:
          cmd: cargo deb -p miner --target=x86_64-unknown-linux-musl
#      - name: Upload Deb Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: amd64deb
#          path: ./target/x86_64-unknown-linux-musl/debian/*
#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v1-release
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: target/release/${{ matrix.artifact_name }}
#          asset_name: ${{ matrix.asset_name }}
#          tag: ${{ github.ref }}
