name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Deb Build
        uses: ebbflow-io/cargo-deb-armv7-debian@1.47.0-1
#      - name: Upload binaries to release
#        uses: svenstaro/upload-release-action@v1-release
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          file: target/release/${{ matrix.artifact_name }}
#          asset_name: ${{ matrix.asset_name }}
#          tag: ${{ github.ref }}
