name: Publish

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always
  NODE_ENV: prod

jobs:
  release:
    name: Release for OLSF
    runs-on: self-hosted

    steps:
      - run: sudo apt install -y cmake clang llvm libgmp-dev pkg-config libssl-dev
      - uses: actions-rs/toolchain@v1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - run: cargo install cargo-deb
      - uses: actions/checkout@v1
      - name: Build
        run:  cargo deb --deb-version ${{ github.ref }} -- -p miner --exclude libra-fuzzer --exclude cluster-test --exclude libra-fuzz
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/miner
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload binaries to release 2
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/*node
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true