name: Publish

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always
  NODE_ENV: prod

jobs:
  release:
    name: Release for OLSF
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          components: rustfmt
      - name: Build
        run:  cargo build -p miner -p libra-node -p ol-cli --release
      - name: Upload `miner` to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/miner
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload `libra-node` to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/*node
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Upload `ol-cli` to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/ol*
          tag: ${{ github.ref }}
          overwrite: true